apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
metadata:
  name: keepalived
spec:
  template:
    spec:
      configMapGenerator:
      - name: ironic-bmo-configmap
        $patch: delete
