apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: mysql
  name: mysql
spec:
  secretName: database-auth-secret
  tlsUseSelfSigned: true
  instances: 3
  podSpec:
    nodeSelector:
      node-role.kubernetes.io/master: "true"
  router:
    instances: 2
    podSpec:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
  datadirVolumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 40Gi
