apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmaps.sssdConfig }}
  annotations:
    "helm.sh/hook": pre-install
data:
  sssd.conf: |
    {{- .Files.Get "files/sssd.conf" | nindent 4 -}}
