# Copyright 2023 Logicalis UKI. All Rights Reserved.
#
# Licensed under the Functional Source License, Version 1.0, Apache 2.0 Change License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/logicalisuki/ubiquity/blob/main/LICENSE.md
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# It also allows for the transition of this software to an Apache 2.0 Licence
# on the second anniversary of the date we make the software available.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-application
  annotations:
    workflows.argoproj.io/description: >-
      Leverages Argo Workflows' ability to interact directly with Kubernetes to deploy an Argo CD Application.
      It monitors the health status of the application and is only considered 'done' once the Argo CD
      Application reports itself as healthy.
    workflows.argoproj.io/maintainer: 'Logicalis UKI'
    workflows.argoproj.io/maintainer_url: 'https://github.com/logicalisuki/ubiquity'
    workflows.argoproj.io/version: '>= 3.4.2'
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:            
        - name: deploy-application
          template: deploy-application

  - name: deploy-application
    resource:
      action: create
      successCondition: status.health.status == Healthy
      failureCondition: status.health.status == Degraded
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: final-application
          finalizers:
            - resources-finalizer.argocd.argoproj.io
          namespace: argocd
        spec:
          destination:
            namespace: final-application
            server: 'https://kubernetes.default.svc'
          project: default
          source:
            path: bootstrap/final-application
            repoURL: 'https://github.com/pipekit/argo-workflows-ci-example.git'
            targetRevision: HEAD
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - PrunePropagationPolicy=background
              - PruneLast=true
              - CreateNamespace=true