---
# Copyright 2023 Logicalis UKI. All Rights Reserved.
#
# Licensed under the Functional Source License, Version 1.0, Apache 2.0 Change License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/logicalisuki/ubiquity/blob/main/LICENSE.md
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# It also allows for the transition of this software to an Apache 2.0 Licence
# on the second anniversary of the date we make the software available.
# See the License for the specific language governing permissions and
# limitations under the License.

# The metal group contains the physical nodes in the cluster
metal:
  children:
    masters:
      hosts:
        cp1: {ansible_host: 10.1.0.1, mac: 'de:ad:be:ef:be:ef', disk: sda, ipmi_addr: 10.0.0.1, ipmi_user: USERID, ipmi_pass: 'PASSW0RD', wol: false }
        cp2: {ansible_host: 10.1.0.2, mac: 'de:ad:be:ef:be:ef', disk: sda, ipmi_addr: 10.0.0.2, ipmi_user: USERID, ipmi_pass: 'PASSW0RD', wol: false }
        cp3: {ansible_host: 10.1.0.3, mac: 'de:ad:be:ef:be:ef', disk: sda, ipmi_addr: 10.0.0.3, ipmi_user: USERID, ipmi_pass: 'PASSW0RD', wol: false }
    workers:
      hosts:
#        worker1: {ansible_host: 192.168.1.121, mac: 'de:ad:be:ef:83:b9', disk: sda, network_interface: eno1, ipmi_addr: 192.168.0.121, ipmi_user: root, ipmi_pass: calvin2, wol: false }
#        worker2: {ansible_host: 192.168.1.122, mac: '90:b1:1c:58:83:b9', disk: sda, network_interface: eno1, ipmi_addr: 192.168.0.122, ipmi_user: root, ipmi_pass: calvin2, wol: false }
#        worker3: {ansible_host: 192.168.1.123, mac: '90:b1:1c:58:83:b9', disk: sda, network_interface: eno1, ipmi_addr: 192.168.0.123, ipmi_user: root, ipmi_pass: calvin2, wol: false }
