# Copyright 2023 Logicalis UKI. All Rights Reserved.
#
# Licensed under the Functional Source License, Version 1.0, Apache 2.0 Change License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/logicalisuki/ubiquity/blob/main/LICENSE.md
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# It also allows for the transition of this software to an Apache 2.0 Licence
# on the second anniversary of the date we make the software available.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Hardening tasks - package manager

# CIS 1.2.1
# CIS 1.2.2
# CIS 1.2.3
# STIG 020050
# STIG 020060
# STIG 020200
- block:

    - name: "Hardening | Ensure GPG check Enabled for Local Packages (Yum)"
      ansible.builtin.ini_file:
        dest: /etc/yum.conf
        section: main
        option: "{{ item.key }}"
        value: "{{ item.value }}"
        create: yes
        owner: 'root'
        group: 'root'
        mode: '0644'
      with_items:
        - {key: fastestmirror, value: true}
        - {key: gpgcheck, value: 1}
        - {key: ip_resolve, value: 4}
        - {key: keepcache, value: true}
        - {key: localpkg_gpgcheck, value: 1}
        - {key: clean_requirements_on_remove, value: 1}

    - name: "Hardening | Ensure GPG check Enabled for Local Packages (DNF)"
      ansible.builtin.ini_file:
        dest: /etc/dnf/dnf.conf
        section: main
        option: "{{ item.key }}"
        value: "{{ item.value }}"
        create: yes
        owner: 'root'
        group: 'root'
        mode: '0644'
      with_items:
        - {key: fastestmirror, value: true}
        - {key: gpgcheck, value: 1}
        - {key: ip_resolve, value: 4}
        - {key: keepcache, value: true}
        - {key: localpkg_gpgcheck, value: 1}
        - {key: clean_requirements_on_remove, value: 1}

    - name: "Hardening | check if rules file exists"
      ansible.builtin.stat: 
        path: /etc/rpm/macros.dist
      register: macros_dist

    - name: "Hardening | Ensure GPG check is globally activated (rpm)"
      ansible.builtin.lineinfile:
        dest: /etc/rpm/macros.dist
        state: present
        regexp: "^%_pkgverify_level.*"
        line: '%_pkgverify_level all'
      when: macros_dist.stat.exists == True
       
  when:
    - ansible_os_family == "RedHat"

...
