apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 84Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - hard
  - timeo=600
  - retrans=3
  - proto=tcp
  - nfsvers=4.2
  - port=2049
  - rsize=1048576
  - wsize=1048576
  - noatime
  - nodiratime
  - fsc
  - nocto
  - nconnect=16
  - actimeo=60
  nfs:
    path: /mnt/nfs
    server: 10.8.0.200
