---
# Copyright 2023 Logicalis UKI. All Rights Reserved.
#
# Licensed under the Functional Source License, Version 1.0, Apache 2.0 Change License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/logicalisuki/ubiquity/blob/main/LICENSE.md
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# It also allows for the transition of this software to an Apache 2.0 Licence
# on the second anniversary of the date we make the software available.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

#############      RBAC     ################

  - rbac.yaml # Slurm


############# Miscellaneous ################
#  - ./misc/build.yaml


########### HTCondor cluster ##################
# - ./htcondor/woo.yaml

## Service accounts
#  - ./htcondor/v2/serviceaccount-creator.yaml
#  - ./htcondor/v2/htcondor-clusterrolebinding.yaml

## Master Services
#  - ./htcondor/v2/htcondor-collector-service.yaml
#  - ./htcondor/v2/htcondor-collector-deployment.yaml
#  - ./htcondor/v2/htcondor-negotiator-deployment.yaml

## Schedd
#  - ./htcondor/v2/htcondor-schedd-deployment.yaml

## Worker
#  - ./htcondor/v2/htcondor-worker-deployment.yaml
#  - ./htcondor/v2/htcondor-worker-configmap.yaml
    
## Autoscaling 

### NO RBAC
#- ./htcondor/v2/htcondor-pool-deployment.yaml

### RBAC
#  - ./htcondor/v2/htcondor-pool-deployment-rbac.yaml

components:

################### Slurm ###################
# Longhorn-backed cluster
   - ./slurm/lh

# NFS-backed cluster
#   - ./slurm/nfs
