kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list-hpc-ubiq
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list-hpc-ubiq
subjects:
- kind: ServiceAccount
  name: default
  namespace: hpc-ubiq
roleRef:
  kind: ClusterRole
  name: pods-list-hpc-ubiq
  apiGroup: rbac.authorization.k8s.io
