---
# Copyright 2023 Logicalis UKI. All Rights Reserved.
#
# Licensed under the Functional Source License, Version 1.0, Apache 2.0 Change License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/logicalisuki/ubiquity/blob/main/LICENSE.md
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# It also allows for the transition of this software to an Apache 2.0 Licence
# on the second anniversary of the date we make the software available.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: htcondor-worker
  name: htcondor-worker
spec:
  selector:
    matchLabels:
      app: htcondor-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: htcondor-worker
    spec:
      containers:
      - name: htcondor-worker
        image: alahiff/htcondor-worker:latest
        resources:
          requests:
            memory: "1.0Gi"
            cpu: "500m"
          limits:
            memory: "1.0Gi"
            cpu: "500m"
        env:
        - name: CONDOR_HOST
          value: "htcondor-central-manager"
        - name: SEC_PASSWORD_FILE
          value: "/etc/condor/pool_password/password"
        volumeMounts:
          - name: pool-password
            mountPath: /etc/condor/pool_password
        ports:
        - containerPort: 9618
          protocol: TCP
      volumes:
      - name: pool-password
        secret:
          defaultMode: 0600
          secretName: htcondor-pool-password
